// <auto-generated />
using System;
using CopaAirlines.RequestsService.DA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CopaAirlines.RequestsService.DA.Migrations
{
    [DbContext(typeof(DBContext_RequestService))]
    partial class DBContext_RequestServiceModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CopaAirlines.RequestsService.DA.DbModel.NameCorrectionRequest", b =>
                {
                    b.Property<long>("NameCorrectionRequestID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgencyID");

                    b.Property<string>("ContactPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("PNR");

                    b.Property<DateTime>("RegisteredDate");

                    b.Property<string>("ServiceLanguage")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.HasKey("NameCorrectionRequestID");

                    b.ToTable("NameCorrectionRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
